package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("InternaOdluka")
public class InternaOdluka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IDInternaOdluka")
   private java.lang.Integer IDInternaOdluka;
   @org.kie.api.definition.type.Label("DatumInterneOdluke")
   private java.util.Date datumInterneOdluke;
   @org.kie.api.definition.type.Label("OpisInterneOdluke")
   private java.lang.String opisInterneOdluke;

   @org.kie.api.definition.type.Label(value = "IDPredstavnici")
   private java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici;

   public InternaOdluka()
   {
   }

   public java.lang.Integer getIDInternaOdluka()
   {
      return this.IDInternaOdluka;
   }

   public void setIDInternaOdluka(java.lang.Integer IDInternaOdluka)
   {
      this.IDInternaOdluka = IDInternaOdluka;
   }

   public java.util.Date getDatumInterneOdluke()
   {
      return this.datumInterneOdluke;
   }

   public void setDatumInterneOdluke(java.util.Date datumInterneOdluke)
   {
      this.datumInterneOdluke = datumInterneOdluke;
   }

   public java.lang.String getOpisInterneOdluke()
   {
      return this.opisInterneOdluke;
   }

   public void setOpisInterneOdluke(java.lang.String opisInterneOdluke)
   {
      this.opisInterneOdluke = opisInterneOdluke;
   }

   public java.util.List<nabavahz.otvoreni.Predstavnici> getIDPredstavnici()
   {
      return this.IDPredstavnici;
   }

   public void setIDPredstavnici(
         java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici)
   {
      this.IDPredstavnici = IDPredstavnici;
   }

   public InternaOdluka(java.lang.Integer IDInternaOdluka,
         java.util.Date datumInterneOdluke, java.lang.String opisInterneOdluke,
         java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici)
   {
      this.IDInternaOdluka = IDInternaOdluka;
      this.datumInterneOdluke = datumInterneOdluke;
      this.opisInterneOdluke = opisInterneOdluke;
      this.IDPredstavnici = IDPredstavnici;
   }

}