package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("InternaOdluka")
public class InternaOdluka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IDInternaOdluka")
   private java.lang.Integer IDInternaOdluka;
   @org.kie.api.definition.type.Label("DatumInterneOdluke")
   private java.util.Date DatumInterneOdluke;
   @org.kie.api.definition.type.Label("OpisInterneOdluke")
   private java.lang.String OpisInterneOdluke;

   @org.kie.api.definition.type.Label("IDPredstavnici")
   private java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici;

   @org.kie.api.definition.type.Label(value = "ImePrezime")
   private java.lang.String ImePrezime;

   @org.kie.api.definition.type.Label(value = "ImePrezime1")
   private java.lang.String ImePrezime1;

   @org.kie.api.definition.type.Label(value = "ImePrezime2")
   private java.lang.String ImePrezime2;

   public InternaOdluka()
   {
   }

   public java.lang.Integer getIDInternaOdluka()
   {
      return this.IDInternaOdluka;
   }

   public void setIDInternaOdluka(java.lang.Integer IDInternaOdluka)
   {
      this.IDInternaOdluka = IDInternaOdluka;
   }

   public java.util.Date getDatumInterneOdluke()
   {
      return this.DatumInterneOdluke;
   }

   public void setDatumInterneOdluke(java.util.Date datumInterneOdluke)
   {
      this.DatumInterneOdluke = datumInterneOdluke;
   }

   public java.lang.String getOpisInterneOdluke()
   {
      return this.OpisInterneOdluke;
   }

   public void setOpisInterneOdluke(java.lang.String opisInterneOdluke)
   {
      this.OpisInterneOdluke = opisInterneOdluke;
   }

   public java.util.List<nabavahz.otvoreni.Predstavnici> getIDPredstavnici()
   {
      return this.IDPredstavnici;
   }

   public void setIDPredstavnici(
         java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici)
   {
      this.IDPredstavnici = IDPredstavnici;
   }

   public InternaOdluka(java.lang.Integer IDInternaOdluka,
         java.util.Date datumInterneOdluke, java.lang.String opisInterneOdluke,
         java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici)
   {
      this.IDInternaOdluka = IDInternaOdluka;
      this.DatumInterneOdluke = datumInterneOdluke;
      this.OpisInterneOdluke = opisInterneOdluke;
      this.IDPredstavnici = IDPredstavnici;
   }

   public java.lang.String getImePrezime()
   {
      return this.ImePrezime;
   }

   public void setImePrezime(java.lang.String imePrezime)
   {
      this.ImePrezime = imePrezime;
   }

   public java.lang.String getImePrezime1()
   {
      return this.ImePrezime1;
   }

   public void setImePrezime1(java.lang.String imePrezime1)
   {
      this.ImePrezime1 = imePrezime1;
   }

   public java.lang.String getImePrezime2()
   {
      return this.ImePrezime2;
   }

   public void setImePrezime2(java.lang.String imePrezime2)
   {
      this.ImePrezime2 = imePrezime2;
   }

   public InternaOdluka(java.lang.Integer IDInternaOdluka,
         java.util.Date DatumInterneOdluke, java.lang.String OpisInterneOdluke,
         java.util.List<nabavahz.otvoreni.Predstavnici> IDPredstavnici,
         java.lang.String imePrezime, java.lang.String imePrezime1,
         java.lang.String imePrezime2)
   {
      this.IDInternaOdluka = IDInternaOdluka;
      this.DatumInterneOdluke = DatumInterneOdluke;
      this.OpisInterneOdluke = OpisInterneOdluke;
      this.IDPredstavnici = IDPredstavnici;
      this.ImePrezime = imePrezime;
      this.ImePrezime1 = imePrezime1;
      this.ImePrezime2 = imePrezime2;
   }

}