package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("OdlukaOdabir")
public class OdlukaOdabir implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDOdlukaOdabir")
   private java.lang.Integer IDOdlukaOdabir;
   @org.kie.api.definition.type.Label(value = "OpisOdabirOdluka")
   private java.lang.String opisOdlukaOdabir;
   @org.kie.api.definition.type.Label(value = "DatumOdabirOdluka")
   private java.util.Date datumOdabirOdluka;

   public OdlukaOdabir()
   {
   }

   public java.lang.Integer getIDOdlukaOdabir()
   {
      return this.IDOdlukaOdabir;
   }

   public void setIDOdlukaOdabir(java.lang.Integer IDOdlukaOdabir)
   {
      this.IDOdlukaOdabir = IDOdlukaOdabir;
   }

   public java.lang.String getOpisOdlukaOdabir()
   {
      return this.opisOdlukaOdabir;
   }

   public void setOpisOdlukaOdabir(java.lang.String opisOdlukaOdabir)
   {
      this.opisOdlukaOdabir = opisOdlukaOdabir;
   }

   public java.util.Date getDatumOdabirOdluka()
   {
      return this.datumOdabirOdluka;
   }

   public void setDatumOdabirOdluka(java.util.Date datumOdabirOdluka)
   {
      this.datumOdabirOdluka = datumOdabirOdluka;
   }

   public OdlukaOdabir(java.lang.Integer IDOdlukaOdabir,
         java.lang.String opisOdlukaOdabir, java.util.Date datumOdabirOdluka)
   {
      this.IDOdlukaOdabir = IDOdlukaOdabir;
      this.opisOdlukaOdabir = opisOdlukaOdabir;
      this.datumOdabirOdluka = datumOdabirOdluka;
   }

}