package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Pojasnjenje")
public class Pojasnjenje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDPojasnjenja")
   private java.lang.Integer IDPojasnjenja;
   @org.kie.api.definition.type.Label(value = "OpisPojasnjenja")
   private java.lang.String OpisPojasnjenja;
   @org.kie.api.definition.type.Label(value = "DatumPojasnjenja")
   private java.util.Date DatumPojasnjenja;

   public Pojasnjenje()
   {
   }

   public java.lang.Integer getIDPojasnjenja()
   {
      return this.IDPojasnjenja;
   }

   public void setIDPojasnjenja(java.lang.Integer IDPojasnjenja)
   {
      this.IDPojasnjenja = IDPojasnjenja;
   }

   public java.lang.String getOpisPojasnjenja()
   {
      return this.OpisPojasnjenja;
   }

   public void setOpisPojasnjenja(java.lang.String opisPojasnjenja)
   {
      this.OpisPojasnjenja = opisPojasnjenja;
   }

   public java.util.Date getDatumPojasnjenja()
   {
      return this.DatumPojasnjenja;
   }

   public void setDatumPojasnjenja(java.util.Date datumPojasnjenja)
   {
      this.DatumPojasnjenja = datumPojasnjenja;
   }

   public Pojasnjenje(java.lang.Integer IDPojasnjenja,
         java.lang.String opisPojasnjenja, java.util.Date datumPojasnjenja)
   {
      this.IDPojasnjenja = IDPojasnjenja;
      this.OpisPojasnjenja = opisPojasnjenja;
      this.DatumPojasnjenja = datumPojasnjenja;
   }

}