package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PonudaZalba")
public class PonudaZalba implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDPonudaZalba")
   private java.lang.Integer IDPonudaZalba;
   @org.kie.api.definition.type.Label(value = "EBN")
   private java.lang.String EBN;
   @org.kie.api.definition.type.Label(value = "DatumPonudaZalba")
   private java.util.Date DatumPonudaZalba;
   @org.kie.api.definition.type.Label(value = "DobavljacPonudaZalba")
   private java.lang.String DobavljacPonudaZalba;
   @org.kie.api.definition.type.Label(value = "Ponuda")
   private java.lang.Boolean Ponuda;
   @org.kie.api.definition.type.Label(value = "Zalba")
   private java.lang.Boolean Zalba;

   public PonudaZalba()
   {
   }

   public java.lang.Integer getIDPonudaZalba()
   {
      return this.IDPonudaZalba;
   }

   public void setIDPonudaZalba(java.lang.Integer IDPonudaZalba)
   {
      this.IDPonudaZalba = IDPonudaZalba;
   }

   public java.lang.String getEBN()
   {
      return this.EBN;
   }

   public void setEBN(java.lang.String EBN)
   {
      this.EBN = EBN;
   }

   public java.util.Date getDatumPonudaZalba()
   {
      return this.DatumPonudaZalba;
   }

   public void setDatumPonudaZalba(java.util.Date datumPonudaZalba)
   {
      this.DatumPonudaZalba = datumPonudaZalba;
   }

   public java.lang.String getDobavljacPonudaZalba()
   {
      return this.DobavljacPonudaZalba;
   }

   public void setDobavljacPonudaZalba(java.lang.String dobavljacPonudaZalba)
   {
      this.DobavljacPonudaZalba = dobavljacPonudaZalba;
   }

   public java.lang.Boolean getPonuda()
   {
      return this.Ponuda;
   }

   public void setPonuda(java.lang.Boolean ponuda)
   {
      this.Ponuda = ponuda;
   }

   public java.lang.Boolean getZalba()
   {
      return this.Zalba;
   }

   public void setZalba(java.lang.Boolean zalba)
   {
      this.Zalba = zalba;
   }

   public PonudaZalba(java.lang.Integer IDPonudaZalba, java.lang.String EBN,
         java.util.Date datumPonudaZalba,
         java.lang.String dobavljacPonudaZalba, java.lang.Boolean ponuda,
         java.lang.Boolean zalba)
   {
      this.IDPonudaZalba = IDPonudaZalba;
      this.EBN = EBN;
      this.DatumPonudaZalba = datumPonudaZalba;
      this.DobavljacPonudaZalba = dobavljacPonudaZalba;
      this.Ponuda = ponuda;
      this.Zalba = zalba;
   }

}