package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PonudeNakonRoka implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PonudeNakonRoka() {
    }

}