package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Predmet nabave")
public class PredmetNabave implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IDPredmeta")
   private java.lang.Integer IDPredmeta;
   @org.kie.api.definition.type.Label("EBN")
   private java.lang.String EBN;
   @org.kie.api.definition.type.Label("OpisPredmeta")
   private java.lang.String OpisPredmeta;

   @org.kie.api.definition.type.Label("IDInternaOdluka")
   private nabavahz.otvoreni.InternaOdluka IDInternaOdluka;

   @org.kie.api.definition.type.Label("AzuriranoPortal")
   private java.lang.Boolean AzuriranoPortal;

   @org.kie.api.definition.type.Label("ObjavaEOJN")
   private java.lang.Boolean ObjavaEOJN;

   @org.kie.api.definition.type.Label("ObjavaPortal")
   private java.lang.Boolean ObjavaPortal;

   @org.kie.api.definition.type.Label("DatumPredmeta")
   private java.util.Date DatumPredmeta;

   @org.kie.api.definition.type.Label("IDPojasnjenje")
   private nabavahz.otvoreni.Pojasnjenje IDPojasnjenje;

   @org.kie.api.definition.type.Label("IDPonudaZalba")
   private PonudaZalba IDPonudaZalba;

   @org.kie.api.definition.type.Label("KontrolaRacunskePogreske")
   private java.lang.Boolean KontrolaRacunskePogreske;

   @org.kie.api.definition.type.Label("IDZapisnikPregledOcjena")
   private nabavahz.otvoreni.ZapisnikPregledOcjena IDZapisnikPregledOcjena;

   @org.kie.api.definition.type.Label("OdlukaOdabirZalba")
   private java.lang.Boolean OdlukaOdabirZalba;

   @org.kie.api.definition.type.Label("IDOdlukaOdabir")
   private nabavahz.otvoreni.OdlukaOdabir IDOdlukaOdabir;

   @org.kie.api.definition.type.Label("IDZapisnikUvidPonude")
   private nabavahz.otvoreni.ZapisnikUvidPonude IDZapisnikUvidPonude;

   @org.kie.api.definition.type.Label("ZalbaOdabir")
   private java.lang.Boolean zalbaOdabir;

   @org.kie.api.definition.type.Label("IDZapisnikOtvaranje")
   private nabavahz.otvoreni.ZapisnikOtvaranje IDZapisnikOtvaranje;

   public PredmetNabave()
   {
   }
      public PredmetNabave(java.lang.Integer IDPredmeta, java.lang.String EBN,
         java.lang.String OpisPredmeta,
         nabavahz.otvoreni.InternaOdluka IDInternaOdluka,
         java.lang.Boolean AzuriranoPortal, java.lang.Boolean ObjavaEOJN,
         java.lang.Boolean ObjavaPortal, java.util.Date DatumPredmeta,
         nabavahz.otvoreni.Pojasnjenje IDPojasnjenje,
         nabavahz.otvoreni.PonudaZalba IDPonudaZalba,
         java.lang.Boolean KontrolaRacunskePogreske,
         nabavahz.otvoreni.ZapisnikPregledOcjena IDZapisnikPregledOcjena,
         java.lang.Boolean OdlukaOdabirZalba,
         nabavahz.otvoreni.OdlukaOdabir IDOdlukaOdabir,
         nabavahz.otvoreni.ZapisnikUvidPonude IDZapisnikUvidPonude,
         java.lang.Boolean zalbaOdabir,
         nabavahz.otvoreni.ZapisnikOtvaranje IDZapisnikOtvaranje)
   {
      this.IDPredmeta = IDPredmeta;
      this.EBN = EBN;
      this.OpisPredmeta = OpisPredmeta;
      this.IDInternaOdluka = IDInternaOdluka;
      this.AzuriranoPortal = AzuriranoPortal;
      this.ObjavaEOJN = ObjavaEOJN;
      this.ObjavaPortal = ObjavaPortal;
      this.DatumPredmeta = DatumPredmeta;
      this.IDPojasnjenje = IDPojasnjenje;
      this.IDPonudaZalba = IDPonudaZalba;
      this.KontrolaRacunskePogreske = KontrolaRacunskePogreske;
      this.IDZapisnikPregledOcjena = IDZapisnikPregledOcjena;
      this.OdlukaOdabirZalba = OdlukaOdabirZalba;
      this.IDOdlukaOdabir = IDOdlukaOdabir;
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
      this.zalbaOdabir = zalbaOdabir;
      this.IDZapisnikOtvaranje = IDZapisnikOtvaranje;
   }

   public java.lang.Integer getIDPredmeta()
   {
      return this.IDPredmeta;
   }

   public void setIDPredmeta(java.lang.Integer IDPredmeta)
   {
      this.IDPredmeta = IDPredmeta;
   }

   public java.lang.String getEBN()
   {
      return this.EBN;
   }

   public void setEBN(java.lang.String EBN)
   {
      this.EBN = EBN;
   }

   public java.lang.String getOpisPredmeta()
   {
      return this.OpisPredmeta;
   }

   public void setOpisPredmeta(java.lang.String opisPredmeta)
   {
      this.OpisPredmeta = opisPredmeta;
   }

   public nabavahz.otvoreni.InternaOdluka getIDInternaOdluka()
   {
      return this.IDInternaOdluka;
   }

   public void setIDInternaOdluka(nabavahz.otvoreni.InternaOdluka IDInternaOdluka)
   {
      this.IDInternaOdluka = IDInternaOdluka;
   }

   public java.lang.Boolean getAzuriranoPortal()
   {
      return this.AzuriranoPortal;
   }

   public void setAzuriranoPortal(java.lang.Boolean azuriranoPortal)
   {
      this.AzuriranoPortal = azuriranoPortal;
   }

   public java.lang.Boolean getObjavaEOJN()
   {
      return this.ObjavaEOJN;
   }

   public void setObjavaEOJN(java.lang.Boolean objavaEOJN)
   {
      this.ObjavaEOJN = objavaEOJN;
   }

   public java.lang.Boolean getObjavaPortal()
   {
      return this.ObjavaPortal;
   }

   public void setObjavaPortal(java.lang.Boolean objavaPortal)
   {
      this.ObjavaPortal = objavaPortal;
   }

   public java.util.Date getDatumPredmeta()
   {
      return this.DatumPredmeta;
   }

   public void setDatumPredmeta(java.util.Date datumPredmeta)
   {
      this.DatumPredmeta = datumPredmeta;
   }

   public nabavahz.otvoreni.Pojasnjenje getIDPojasnjenje()
   {
      return this.IDPojasnjenje;
   }

   public void setIDPojasnjenje(nabavahz.otvoreni.Pojasnjenje IDPojasnjenje)
   {
      this.IDPojasnjenje = IDPojasnjenje;
   }

   public java.lang.Boolean getKontrolaRacunskePogreske()
   {
      return this.KontrolaRacunskePogreske;
   }

   public void setKontrolaRacunskePogreske(
         java.lang.Boolean kontrolaRacunskePogreske)
   {
      this.KontrolaRacunskePogreske = kontrolaRacunskePogreske;
   }

   public nabavahz.otvoreni.ZapisnikPregledOcjena getIDZapisnikPregledOcjena()
   {
      return this.IDZapisnikPregledOcjena;
   }

   public void setIDZapisnikPregledOcjena(
         nabavahz.otvoreni.ZapisnikPregledOcjena IDZapisnikPregledOcjena)
   {
      this.IDZapisnikPregledOcjena = IDZapisnikPregledOcjena;
   }

   public java.lang.Boolean getOdlukaOdabirZalba()
   {
      return this.OdlukaOdabirZalba;
   }

   public void setOdlukaOdabirZalba(java.lang.Boolean odlukaOdabirZalba)
   {
      this.OdlukaOdabirZalba = odlukaOdabirZalba;
   }

   public nabavahz.otvoreni.OdlukaOdabir getIDOdlukaOdabir()
   {
      return this.IDOdlukaOdabir;
   }

   public void setIDOdlukaOdabir(nabavahz.otvoreni.OdlukaOdabir IDOdlukaOdabir)
   {
      this.IDOdlukaOdabir = IDOdlukaOdabir;
   }

   public nabavahz.otvoreni.ZapisnikUvidPonude getIDZapisnikUvidPonude()
   {
      return this.IDZapisnikUvidPonude;
   }

   public void setIDZapisnikUvidPonude(
         nabavahz.otvoreni.ZapisnikUvidPonude IDZapisnikUvidPonude)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
   }

   public java.lang.Boolean getZalbaOdabir()
   {
      return this.zalbaOdabir;
   }

   public void setZalbaOdabir(java.lang.Boolean zalbaOdabir)
   {
      this.zalbaOdabir = zalbaOdabir;
   }

   public nabavahz.otvoreni.ZapisnikOtvaranje getIDZapisnikOtvaranje()
   {
      return this.IDZapisnikOtvaranje;
   }

   public void setIDZapisnikOtvaranje(
         nabavahz.otvoreni.ZapisnikOtvaranje IDZapisnikOtvaranje)
   {
      this.IDZapisnikOtvaranje = IDZapisnikOtvaranje;
   }

   public nabavahz.otvoreni.PonudaZalba getIDPonudaZalba()
   {
      return this.IDPonudaZalba;
   }

   public void setIDPonudaZalba(nabavahz.otvoreni.PonudaZalba IDPonudaZalba)
   {
      this.IDPonudaZalba = IDPonudaZalba;
   }



}