package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Predmet nabave")
public class PredmetNabave implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IDPredmeta")
   private java.lang.Integer IDPredmeta;
   @org.kie.api.definition.type.Label("EBN")
   private java.lang.String EBN;
   @org.kie.api.definition.type.Label("DatumPredmeta")
   private java.util.Date datumPredmeta;
   @org.kie.api.definition.type.Label("OpisPredmeta")
   private java.lang.String opisPredmeta;

   @org.kie.api.definition.type.Label("IDInternaOdluka")
   private nabavahz.otvoreni.InternaOdluka IDInternaOdluka;

   @org.kie.api.definition.type.Label(value = "AzuriranoPortal")
   private java.lang.Boolean azuriranoPortal;

   public PredmetNabave()
   {
   }

   public java.lang.Integer getIDPredmeta()
   {
      return this.IDPredmeta;
   }

   public void setIDPredmeta(java.lang.Integer IDPredmeta)
   {
      this.IDPredmeta = IDPredmeta;
   }

   public java.lang.String getEBN()
   {
      return this.EBN;
   }

   public void setEBN(java.lang.String EBN)
   {
      this.EBN = EBN;
   }

   public java.util.Date getDatumPredmeta()
   {
      return this.datumPredmeta;
   }

   public void setDatumPredmeta(java.util.Date datumPredmeta)
   {
      this.datumPredmeta = datumPredmeta;
   }

   public java.lang.String getOpisPredmeta()
   {
      return this.opisPredmeta;
   }

   public void setOpisPredmeta(java.lang.String opisPredmeta)
   {
      this.opisPredmeta = opisPredmeta;
   }

   public nabavahz.otvoreni.InternaOdluka getIDInternaOdluka()
   {
      return this.IDInternaOdluka;
   }

   public void setIDInternaOdluka(nabavahz.otvoreni.InternaOdluka IDInternaOdluka)
   {
      this.IDInternaOdluka = IDInternaOdluka;
   }

   public java.lang.Boolean getAzuriranoPortal()
   {
      return this.azuriranoPortal;
   }

   public void setAzuriranoPortal(java.lang.Boolean azuriranoPortal)
   {
      this.azuriranoPortal = azuriranoPortal;
   }

   public PredmetNabave(java.lang.Integer IDPredmeta, java.lang.String EBN,
         java.util.Date datumPredmeta, java.lang.String opisPredmeta,
         nabavahz.otvoreni.InternaOdluka IDInternaOdluka,
         java.lang.Boolean azuriranoPortal)
   {
      this.IDPredmeta = IDPredmeta;
      this.EBN = EBN;
      this.datumPredmeta = datumPredmeta;
      this.opisPredmeta = opisPredmeta;
      this.IDInternaOdluka = IDInternaOdluka;
      this.azuriranoPortal = azuriranoPortal;
   }

}