package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Upisnik")
public class Upisnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDUpisnik")
   private java.lang.Integer IDUpisnik;
   @org.kie.api.definition.type.Label(value = "DatumUpisnika")
   private java.util.Date datumUpisnika;
   @org.kie.api.definition.type.Label(value = "IDPonudaZalba")
   private nabavahz.otvoreni.PonudaZalba IDPonudaZalba;

   public Upisnik()
   {
   }

   public java.lang.Integer getIDUpisnik()
   {
      return this.IDUpisnik;
   }

   public void setIDUpisnik(java.lang.Integer IDUpisnik)
   {
      this.IDUpisnik = IDUpisnik;
   }

   public java.util.Date getDatumUpisnika()
   {
      return this.datumUpisnika;
   }

   public void setDatumUpisnika(java.util.Date datumUpisnika)
   {
      this.datumUpisnika = datumUpisnika;
   }

   public nabavahz.otvoreni.PonudaZalba getIDPonudaZalba()
   {
      return this.IDPonudaZalba;
   }

   public void setIDPonudaZalba(nabavahz.otvoreni.PonudaZalba IDPonudaZalba)
   {
      this.IDPonudaZalba = IDPonudaZalba;
   }

   public Upisnik(java.lang.Integer IDUpisnik, java.util.Date datumUpisnika,
         nabavahz.otvoreni.PonudaZalba IDPonudaZalba)
   {
      this.IDUpisnik = IDUpisnik;
      this.datumUpisnika = datumUpisnika;
      this.IDPonudaZalba = IDPonudaZalba;
   }

}