package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Upisnik implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Upisnik() {
    }

}