package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ZapisnikUvidPonude")
public class ZapisnikUvidPonude implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDZapisnikUvidPonude")
   private java.lang.Integer IDZapisnikUvidPonude;
   @org.kie.api.definition.type.Label(value = "Dobavljac")
   private java.lang.String Dobavljac;
   @org.kie.api.definition.type.Label(value = "DatumZapisnika")
   private java.util.Date DatumZapisnika;

   public ZapisnikUvidPonude()
   {
   }

   public java.lang.Integer getIDZapisnikUvidPonude()
   {
      return this.IDZapisnikUvidPonude;
   }

   public void setIDZapisnikUvidPonude(java.lang.Integer IDZapisnikUvidPonude)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
   }

   public java.lang.String getDobavljac()
   {
      return this.Dobavljac;
   }

   public void setDobavljac(java.lang.String dobavljac)
   {
      this.Dobavljac = dobavljac;
   }

   public java.util.Date getDatumZapisnika()
   {
      return this.DatumZapisnika;
   }

   public void setDatumZapisnika(java.util.Date datumZapisnika)
   {
      this.DatumZapisnika = datumZapisnika;
   }

   public ZapisnikUvidPonude(java.lang.Integer IDZapisnikUvidPonude,
         java.lang.String dobavljac, java.util.Date datumZapisnika)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
      this.Dobavljac = dobavljac;
      this.DatumZapisnika = datumZapisnika;
   }

}