package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ZapisnikPregledOcjena")
public class ZapisnikPregledOcjena implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDZapisnikPregledOcjena")
   private java.lang.Integer IDZapisnikPregledOcjena;
   @org.kie.api.definition.type.Label(value = "OpisZapisnika")
   private java.lang.String opisZapisnika;
   @org.kie.api.definition.type.Label(value = "DatumZapisnika")
   private java.util.Date datumZapisnika;

   public ZapisnikPregledOcjena()
   {
   }

   public java.lang.Integer getIDZapisnikPregledOcjena()
   {
      return this.IDZapisnikPregledOcjena;
   }

   public void setIDZapisnikPregledOcjena(
         java.lang.Integer IDZapisnikPregledOcjena)
   {
      this.IDZapisnikPregledOcjena = IDZapisnikPregledOcjena;
   }

   public java.lang.String getOpisZapisnika()
   {
      return this.opisZapisnika;
   }

   public void setOpisZapisnika(java.lang.String opisZapisnika)
   {
      this.opisZapisnika = opisZapisnika;
   }

   public java.util.Date getDatumZapisnika()
   {
      return this.datumZapisnika;
   }

   public void setDatumZapisnika(java.util.Date datumZapisnika)
   {
      this.datumZapisnika = datumZapisnika;
   }

   public ZapisnikPregledOcjena(java.lang.Integer IDZapisnikPregledOcjena,
         java.lang.String opisZapisnika, java.util.Date datumZapisnika)
   {
      this.IDZapisnikPregledOcjena = IDZapisnikPregledOcjena;
      this.opisZapisnika = opisZapisnika;
      this.datumZapisnika = datumZapisnika;
   }

}