package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZapisnikOtvaranje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "IDZapisnikOtvaranje")
   private java.lang.Integer IDZapisnikOtvaranje;
   @org.kie.api.definition.type.Label(value = "DatumZapisnikOtvaranje")
   private java.util.Date datumZapisnikOtvaranje;
   @org.kie.api.definition.type.Label(value = "OpisZapisnikOtvaranje")
   private java.lang.String opisZapisnikOtvaranje;

   public ZapisnikOtvaranje()
   {
   }

   public java.lang.Integer getIDZapisnikOtvaranje()
   {
      return this.IDZapisnikOtvaranje;
   }

   public void setIDZapisnikOtvaranje(java.lang.Integer IDZapisnikOtvaranje)
   {
      this.IDZapisnikOtvaranje = IDZapisnikOtvaranje;
   }

   public java.util.Date getDatumZapisnikOtvaranje()
   {
      return this.datumZapisnikOtvaranje;
   }

   public void setDatumZapisnikOtvaranje(java.util.Date datumZapisnikOtvaranje)
   {
      this.datumZapisnikOtvaranje = datumZapisnikOtvaranje;
   }

   public java.lang.String getOpisZapisnikOtvaranje()
   {
      return this.opisZapisnikOtvaranje;
   }

   public void setOpisZapisnikOtvaranje(java.lang.String opisZapisnikOtvaranje)
   {
      this.opisZapisnikOtvaranje = opisZapisnikOtvaranje;
   }

   public ZapisnikOtvaranje(java.lang.Integer IDZapisnikOtvaranje,
         java.util.Date datumZapisnikOtvaranje,
         java.lang.String opisZapisnikOtvaranje)
   {
      this.IDZapisnikOtvaranje = IDZapisnikOtvaranje;
      this.datumZapisnikOtvaranje = datumZapisnikOtvaranje;
      this.opisZapisnikOtvaranje = opisZapisnikOtvaranje;
   }

}