package nabavahz.otvoreni;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ZapisnikUvidPonude")
public class ZapisnikUvidPonude implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IDZapisnikUvidPonude")
   private java.lang.Integer IDZapisnikUvidPonude;
   @org.kie.api.definition.type.Label("Dobavljac")
   private java.lang.String Dobavljac;
   @org.kie.api.definition.type.Label("DatumZapisnika")
   private java.util.Date DatumZapisnika;

   @org.kie.api.definition.type.Label(value = "OpisZapisnika")
   private java.lang.String opisZapisnika;

   public ZapisnikUvidPonude()
   {
   }

   public java.lang.Integer getIDZapisnikUvidPonude()
   {
      return this.IDZapisnikUvidPonude;
   }

   public void setIDZapisnikUvidPonude(java.lang.Integer IDZapisnikUvidPonude)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
   }

   public java.lang.String getDobavljac()
   {
      return this.Dobavljac;
   }

   public void setDobavljac(java.lang.String dobavljac)
   {
      this.Dobavljac = dobavljac;
   }

   public java.util.Date getDatumZapisnika()
   {
      return this.DatumZapisnika;
   }

   public void setDatumZapisnika(java.util.Date datumZapisnika)
   {
      this.DatumZapisnika = datumZapisnika;
   }

   public ZapisnikUvidPonude(java.lang.Integer IDZapisnikUvidPonude,
         java.lang.String dobavljac, java.util.Date datumZapisnika)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
      this.Dobavljac = dobavljac;
      this.DatumZapisnika = datumZapisnika;
   }

   public java.lang.String getOpisZapisnika()
   {
      return this.opisZapisnika;
   }

   public void setOpisZapisnika(java.lang.String opisZapisnika)
   {
      this.opisZapisnika = opisZapisnika;
   }

   public ZapisnikUvidPonude(java.lang.Integer IDZapisnikUvidPonude,
         java.lang.String Dobavljac, java.util.Date DatumZapisnika,
         java.lang.String opisZapisnika)
   {
      this.IDZapisnikUvidPonude = IDZapisnikUvidPonude;
      this.Dobavljac = Dobavljac;
      this.DatumZapisnika = DatumZapisnika;
      this.opisZapisnika = opisZapisnika;
   }

}